name: dartssh
version: 1.0.4+4
description: Dart SSH package providing First-class tunnelling primitives.
author: Green Appers, Inc. <greenappers@gmail.com>, SteelSavant

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  asn1lib: ^0.8.1
  convert: ^3.0.0
  meta: ^1.3.0
  http: ^0.12.1
  pedantic: ^1.11.0
  pointycastle: ^2.0.1
  validators: ^2.0.0+1

dev_dependencies:
  build_runner: ^1.4.0
  test: ^1.6.5
