name: dartssh
version: 1.0.4+4
description: Dart SSH package providing First-class tunnelling primitives.
author: Green Appers, Inc. <greenappers@gmail.com>, SteelSavant

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  asn1lib: ^1.0.2
  convert: ^3.0.0
  meta: ^1.3.0
  http: ^0.13.1
  pedantic: ^1.11.0
  pointycastle: ^3.3.4
  validators: ^3.0.0

dev_dependencies:
  build_runner: ^2.1.2
  test: ^1.6.5
